/* Autogenerated with kurento-module-creator */

#ifndef __COLOR_DETECTOR_FILTER_IMPL_HPP__
#define __COLOR_DETECTOR_FILTER_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "ColorDetectorFilter.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "ColorDetectorFilterOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace colordetectorfilter
{
class ColorDetectorFilterImpl;
} /* colordetectorfilter */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::colordetectorfilter::ColorDetectorFilterImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace colordetectorfilter
{

class ColorDetectorFilterImpl : public OpenCVFilterImpl, public virtual ColorDetectorFilter, public virtual ColorDetectorFilterOpenCVImpl
{

public:

  ColorDetectorFilterImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~ColorDetectorFilterImpl() = default;

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* colordetectorfilter */
} /* module */
} /* kurento */

#endif /*  __COLOR_DETECTOR_FILTER_IMPL_HPP__ */
