/* Autogenerated with kurento-module-creator */

#ifndef __COLOR_DETECTOR_FILTER_OPENCV_IMPL_HPP__
#define __COLOR_DETECTOR_FILTER_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "ColorDetectorFilter.hpp"
#include <EventHandler.hpp>

namespace kurento
{
namespace module
{
namespace colordetectorfilter
{

class ColorDetectorFilterOpenCVImpl : public virtual OpenCVProcess
{

public:

  ColorDetectorFilterOpenCVImpl ();

  virtual ~ColorDetectorFilterOpenCVImpl() = default;

  virtual void process (cv::Mat &mat);
  sigc::signal<void, ColorDetected> signalColorDetected;

};

} /* colordetectorfilter */
} /* module */
} /* kurento */

#endif /*  __COLOR_DETECTOR_FILTER_OPENCV_IMPL_HPP__ */
