/* Autogenerated with kurento-module-creator */

#ifndef __COLOR_DETECTOR_IMPL_HPP__
#define __COLOR_DETECTOR_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "colorDetector.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "colorDetectorOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace colordetector
{
class colorDetectorImpl;
} /* colordetector */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::colordetector::colorDetectorImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace colordetector
{

class colorDetectorImpl : public OpenCVFilterImpl, public virtual colorDetector, public virtual colorDetectorOpenCVImpl
{

public:

  colorDetectorImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~colorDetectorImpl() = default;

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* colordetector */
} /* module */
} /* kurento */

#endif /*  __COLOR_DETECTOR_IMPL_HPP__ */
