/* Autogenerated with kurento-module-creator */

#ifndef __COLOR_DETECTOR_OPENCV_IMPL_HPP__
#define __COLOR_DETECTOR_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "colorDetector.hpp"
#include <EventHandler.hpp>

namespace kurento
{
namespace module
{
namespace colordetector
{

class colorDetectorOpenCVImpl : public virtual OpenCVProcess
{

public:

  colorDetectorOpenCVImpl ();

  virtual ~colorDetectorOpenCVImpl() = default;

  virtual void process (cv::Mat &mat);
  sigc::signal<void, ColorDetected> signalColorDetected;

};

} /* colordetector */
} /* module */
} /* kurento */

#endif /*  __COLOR_DETECTOR_OPENCV_IMPL_HPP__ */
